# If you want to support this project financially, configure one of these
# channels and the GitHub UI shows a "Sponsor" button on the repo.
# Docs: https://docs.github.com/sponsors

github: [tounsii007]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# liberapay:
# issuehunt:
# polar:
# buy_me_a_coffee:
# custom: ['https://example.com/donate']
